language: ruby
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis;' -U postgres # "travis" is the UNIX username, and therefore the default database name on connection
rvm:
  - 2.1.2
  - 2.0.0
